/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boatSink;

//comentario de prueba
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
