/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controllers;

import org.junit.Test;

import controller.BattleShipController;
import utils.Constants;

import static org.junit.Assert.*;

public class BattleShipControllerTest {
    @Test 
    public void testPlayerName() {
    	BattleShipController battleShipController = new BattleShipController();
    	
    	boolean result1 = battleShipController.isCorrectPlayerName("");
        assertFalse(result1);   
        
    	boolean result2 = battleShipController.isCorrectPlayerName("hola");
        assertTrue(result2);   
    }
    
    @Test
    public void testShipOrientation() {
    	BattleShipController battleShipController = new BattleShipController();
    	
    	boolean result1 = battleShipController.isCorrectShipOrientation("");
    	assertFalse(result1);
    	
    	boolean result2 = battleShipController.isCorrectShipOrientation("test");
    	assertFalse(result2);
    	
    	boolean result4 = battleShipController.isCorrectShipOrientation("-1");
    	assertFalse(result4);
    	
    	boolean result3 = battleShipController.isCorrectShipOrientation("2");
    	assertFalse(result3);
    	
    	boolean result5 = battleShipController.isCorrectShipOrientation(Constants.SHIP_HORIZONTAL);
    	assertTrue(result5);
    	
    	boolean result6 = battleShipController.isCorrectShipOrientation(Constants.SHIP_VERTICAL);
    	assertTrue(result6);
    	
    	boolean result7 = battleShipController.isCorrectShipOrientation("H");
    	assertFalse(result7);
    	
    	boolean result8 = battleShipController.isCorrectShipOrientation("V");
    	assertFalse(result8);
    	
    	boolean result9 = battleShipController.isCorrectShipOrientation("test");
    	assertFalse(result9);
    }
    
    @Test
    public void testShipCoordinate() {
    	BattleShipController battleShipController = new BattleShipController();
    	
    	boolean res1 = battleShipController.isCorrectInputCoordinate("-1");
    	assertFalse(res1);
    	
    	boolean res2 = battleShipController.isCorrectInputCoordinate("0");
    	assertTrue(res2);
    	
    	boolean res3 = battleShipController.isCorrectInputCoordinate("1");
    	assertTrue(res3);
    	
    	boolean res4 = battleShipController.isCorrectInputCoordinate(Integer.toString(Constants.N_BOARD_ROWS_CELLS-1));
    	assertTrue(res4);
  
    	boolean res5 = battleShipController.isCorrectInputCoordinate(Integer.toString(Constants.N_BOARD_ROWS_CELLS));
    	assertFalse(res5);
    	
    	boolean res7 = battleShipController.isCorrectInputCoordinate("test");
    	assertFalse(res7);
    }
    
    @Test 
    public void testEndOfGame() {
    	//BattleShipController battleShipController = new BattleShipController();
    }
}
